# ============================================markdown-preview==============================================
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install'
hook_source = '''
source $XDG_CONFIG_HOME/nvim/plugs/markdown-preview.vim
'''

# ============================================fzf==============================================
[[plugins]]
repo = 'junegunn/fzf'
"build = './install --bin'
"merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_cmd = [
    'Files',
    'ProjectFiles',
    'Buffers',
    'BLines',
    'History',
    'Tags',
    'BTags',
    'GFiles',
    'Rg',
]
hook_add = '''
if executable('rg')
  nnoremap <silent> ,a :<C-u>Rg<CR>
endif
nnoremap <silent> ,f :<C-u>ProjectFiles<CR>
nnoremap <silent> ,b :<C-u>Buffers<CR>
nnoremap <silent> ,m :<C-u>History<CR>
set rtp+=$XDG_CACHE_HOME/fzf
" set rtp+=~/.fzf
'''
hook_source = '''
source $XDG_CONFIG_HOME/nvim/plugs/fzf.vim
'''
# =====================================nvim-treesitter======================================
#syntax highlighting
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = """
    source $XDG_CONFIG_HOME/nvim/plugs/tree-sitter.lua
"""

# ============================================VCoolor==============================================
[[plugins]]
repo = 'KabbAmine/VCoolor.vim'

# ============================================vim-css-color==============================================
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'tsx']
